### ISSUE TITLE
Gaussian pulses not starting at 0

### ISSUE THREAD

**Issue by andbe91** [Labber-software/Drivers#57]
When defining a Gaussian pulse with either the single or the multi qubit pulse generator, the pulse does not start at zero. 
![image](https://user-images.githubusercontent.com/23558186/33474993-fd01caea-d67c-11e7-81d2-e5b5fc57f9ae.png)

This leads to extra spectral content in the pulses, unless you use a large truncation range.

I suggest to subtract the minimum value from the pulse after truncation and then rescale the amplitude to achieve the desired amplitude. I'm happy to implement this myself if you agree that this is a good idea.

**Comment by simongus** [comment]
Sure, that’s reasonable.  We usually use a larger truncation range (3), so that these effects become negligible given the resolution of the AWG.  Can you add a checkbox turning this feature on/off, and put it right below the “Truncation range” parameter?  Also, there is the question as to whether the pulse should still have the full amplitude after truncation, since subtracting the offset will change the height.  Another way to do it would be to smooth out the step by halving the amplitudes of the first/last point, which would maintain the overall shape (and more importantly for qubit driving, the area) of the pulse. 

I’m fine either way, but we should define a consistent behavior.

**Comment by andbe91** [comment]
Closed
