### ISSUE TITLE
DRAG scaling

### ISSUE THREAD

**Issue by andbe91** [Labber-software/Drivers#59]
At the moment, the DRAG scaling parameter needs to be some very small number to get a resonable amplitude. E.g, if I set that parameter to 1, the amplitude of the derivative channel is in the 1e7 range.
I suggest that DRAG scaling=1 should equal the same amplitude of the Gaussian and the derivative channels.

**Comment by simongus** [comment]
The DRAG coefficient is scaling a derivative, and since the pulses are typically 1V / 1 ns, the derivative is numerically large, and the DRAG coefficient needs to be order 1E-10 to bring the values back to ~V range.  Ssince all other units are SI, and since there is a theoretical optimal drag coefficient given by a relation involving the anharmonicity of the system, it seems better to keep the mathematically correct definition to avoid confusion what the parameter means.

Also, setting DRAG scaling =1 to equal the pulse amplitude would result in incorrect pulses if you decided to change the pulse width, whereas with the current definition you only need to tune DRAG once, irrespective of what pulse shape you end up using.
